### ISSUE TITLE
Highlighting names doesn't work properly

### ISSUE THREAD

**Issue by Dimozavr** [leokostarev/algo-code-enhancer#2]
If you have more than one person from one class in your searching menu, than only one of them will be highlighted in your table.
Works for example for A' class and names "Умнов Максим" and "Марченко Алексей"
![image](https://github.com/user-attachments/assets/d1cae0c1-3ea5-43d3-a4a3-2eb688853b99)
![image](https://github.com/user-attachments/assets/d028aefc-eb0c-42b4-9820-d4aa7b6813e0)

**Comment by leokostarev** [comment]
The feature is described poorly. It is highlighting one row, because it is the row, the tasks are colored from.
In 1.4 there will be two fields: for your name and for your friends.
